---
platforms:
  - name: ansible-role-docker-debian-12
    image: debian:12
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
